/**
 * Data Modul & Bank Soal Choukai CBT Platform
 * Kurikulum IMM Japan テキスト (Bab 08 s.d. Bab 25)
 */

const CHAPTERS_INDEX = [
  {
    num: "08",
    title_ja: "第8課：形容詞と職場の様子",
    title_id: "Bab 08: Kata Sifat & Suasana Kerja",
    topic_id: "Kata Sifat-I, Kata Sifat-Na, Peralatan Kerja & Asrama",
    available: true,
    totalQuestions: 8,
    audioDuration: "08:35",
    passingScore: 80,
    badge: "Tersedia",
  },
  {
    num: "09",
    title_ja: "第9課：好き・嫌い・上手・下手",
    title_id: "Bab 09: Kesukaan & Kemahiran",
    topic_id: "Kesenangan, Olahraga, Kemampuan Bahasa, Alasan (~から)",
    available: false,
    totalQuestions: 8,
    audioDuration: "08:15",
    passingScore: 80,
    badge: "Segera Hadir",
  },
  {
    num: "10",
    title_ja: "第10課：存在と位置表現",
    title_id: "Bab 10: Keberadaan & Letak Benda",
    topic_id: "います / あります, Posisi Atas, Bawah, Dalam, Luar, Samping",
    available: false,
    totalQuestions: 8,
    audioDuration: "08:20",
    passingScore: 80,
    badge: "Segera Hadir",
  },
  {
    num: "11",
    title_ja: "第11課：数量詞と期間",
    title_id: "Bab 11: Satuan Bilangan & Jangka Waktu",
    topic_id: "Hitungan Jumlah Barang, Orang, Jam, Hari, Frekuensi",
    available: false,
    totalQuestions: 8,
    audioDuration: "08:30",
    passingScore: 80,
    badge: "Segera Hadir",
  },
  {
    num: "12",
    title_ja: "第12課：比較表現",
    title_id: "Bab 12: Kalimat Perbandingan",
    topic_id: "より～のほうが, どちらが, 一番～ (Perbandingan Tempat & Benda)",
    available: false,
    totalQuestions: 8,
    audioDuration: "08:10",
    passingScore: 80,
    badge: "Segera Hadir",
  },
  {
    num: "13",
    title_ja: "第13課：希望と目的",
    title_id: "Bab 13: Keinginan & Tujuan Perjalanan",
    topic_id: "～がほしい, ～たい, ～へ～に行きます",
    available: false,
    totalQuestions: 8,
    audioDuration: "08:25",
    passingScore: 80,
    badge: "Segera Hadir",
  },
  {
    num: "14",
    title_ja: "第14課：て形と指示・依頼",
    title_id: "Bab 14: Bentuk Te & Permohonan Kerja",
    topic_id: "Bentuk -te, ～てください (Instruksi Pabrik & K3)",
    available: false,
    totalQuestions: 8,
    audioDuration: "08:40",
    passingScore: 80,
    badge: "Segera Hadir",
  },
  {
    num: "15",
    title_ja: "第15課：許可と禁止",
    title_id: "Bab 15: Izin & Larangan",
    topic_id: "～てもいいです, ～てはいけません (Aturan K3 & Keamanan)",
    available: false,
    totalQuestions: 8,
    audioDuration: "08:15",
    passingScore: 80,
    badge: "Segera Hadir",
  },
  {
    num: "16",
    title_ja: "第16課：動作の順序と方法",
    title_id: "Bab 16: Urutan Aksi & Metode",
    topic_id: "～てから, ～て、～て, Bagaimana Cara Mengoperasikan Mesin",
    available: false,
    totalQuestions: 8,
    audioDuration: "08:30",
    passingScore: 80,
    badge: "Segera Hadir",
  },
  {
    num: "17",
    title_ja: "第17課：ない形と義務",
    title_id: "Bab 17: Bentuk Nai & Kewajiban",
    topic_id: "～ないでください, ～なければなりません (Disiplin Kerja)",
    available: false,
    totalQuestions: 8,
    audioDuration: "08:35",
    passingScore: 80,
    badge: "Segera Hadir",
  },
  {
    num: "18",
    title_ja: "第18課：辞書形と能力・趣味",
    title_id: "Bab 18: Bentuk Kamus & Kemampuan",
    topic_id: "～ことができます, 趣味は～ことです, ～の前に",
    available: false,
    totalQuestions: 8,
    audioDuration: "08:20",
    passingScore: 80,
    badge: "Segera Hadir",
  },
  {
    num: "19",
    title_ja: "第19課：た形と経験",
    title_id: "Bab 19: Bentuk Ta & Pengalaman",
    topic_id: "～たことがあります, ～たり～たりします, ～くなります",
    available: false,
    totalQuestions: 8,
    audioDuration: "08:25",
    passingScore: 80,
    badge: "Segera Hadir",
  },
  {
    num: "20",
    title_ja: "第20課：普通形と会話",
    title_id: "Bab 20: Bentuk Biasa (Futsuukei)",
    topic_id: "Percakapan Kasual antar Rekan Asrama & Pabrik",
    available: false,
    totalQuestions: 8,
    audioDuration: "08:15",
    passingScore: 80,
    badge: "Segera Hadir",
  },
  {
    num: "21",
    title_ja: "第21課：意見と推量",
    title_id: "Bab 21: Pendapat & Dugaan",
    topic_id: "～と思います, ～と言いました, ～でしょう",
    available: false,
    totalQuestions: 8,
    audioDuration: "08:30",
    passingScore: 80,
    badge: "Segera Hadir",
  },
  {
    num: "22",
    title_ja: "第22課：連体修飾",
    title_id: "Bab 22: Modifikasi Frasa Benda",
    topic_id: "Kalimat Penjelas Kata Benda (Benda/Orang yang Dilakukan)",
    available: false,
    totalQuestions: 8,
    audioDuration: "08:40",
    passingScore: 80,
    badge: "Segera Hadir",
  },
  {
    num: "23",
    title_ja: "第23課：時と条件",
    title_id: "Bab 23: Waktu & Hubungan Sebab Akibat",
    topic_id: "～とき, ～と (Bila Menekan Tombol Mesin)",
    available: false,
    totalQuestions: 8,
    audioDuration: "08:35",
    passingScore: 80,
    badge: "Segera Hadir",
  },
  {
    num: "24",
    title_ja: "第24課：授受表現",
    title_id: "Bab 24: Memberi & Menerima Bantuan",
    topic_id: "くれます, あげます, もらいます (Bantuan Rekan Senior)",
    available: false,
    totalQuestions: 8,
    audioDuration: "08:25",
    passingScore: 80,
    badge: "Segera Hadir",
  },
  {
    num: "25",
    title_ja: "第25課：仮定条件",
    title_id: "Bab 25: Pengandaian & Syarat Lanjutan",
    topic_id: "～たら, ～ても (Syarat & Tindakan Darurat)",
    available: false,
    totalQuestions: 8,
    audioDuration: "08:45",
    passingScore: 80,
    badge: "Segera Hadir",
  },
];

const BAB_08_DATA = {
  chapter: "08",
  title_ja: "第8課 聞き取り評価試験",
  title_id: "Ujian Mendengarkan Bab 08",
  theme_ja: "形容詞（い形容詞・な形容詞）と職場の様子",
  theme_id: "Kata Sifat (I & Na) dan Suasana Tempat Kerja",
  audioSrc: "assets/Choukai_Bab_08.mp3",
  pdfSoalUrl: "assets/pdf/Soal Choukai Bab 08.pdf",
  pdfKunciUrl: "assets/pdf/Kunci dan Pembahasan Choukai Bab 08.pdf",
  passingGrade: 80,
  questions: [
    {
      id: 1,
      type: "gambar",
      section_ja: "第1部：イラスト理解",
      section_id: "Bagian 1: Pemahaman Ilustrasi",
      audioTimestamp: "00:17",
      audioStartSeconds: 17.4,
      question_ja: "男の人はどの帽子をかぶりますか。",
      question_ruby: "<ruby>男<rt>おとこ</rt></ruby>の<ruby>人<rt>ひと</rt></ruby>はどの<ruby>帽子<rt>ぼうし</rt></ruby>をかぶりますか。",
      question_romaji: "Otoko no hito wa dono boushi o kaburimasu ka.",
      question_id: "Laki-laki tersebut akan mengenakan topi yang mana?",
      image: "assets/bab_08/q1.png",
      options: [
        { id: "1", symbol: "①", text_ja: "① 古い白い帽子（めがねなし）", text_id: "Topi putih usang (tanpa kacamata)" },
        { id: "2", symbol: "②", text_ja: "② 古い白い帽子（めがねあり）", text_id: "Topi putih usang (dengan kacamata)" },
        { id: "3", symbol: "③", text_ja: "③ 新しい青い帽子（めがねなし）", text_id: "Topi biru baru (tanpa kacamata)" },
        { id: "4", symbol: "④", text_ja: "④ 新しい青い帽子（めがねあり）", text_id: "Topi biru baru (dengan kacamata)" },
      ],
      correctAnswer: "3",
      dialogue: [
        {
          speaker: "Agus (アグス)",
          text_ja: "鈴木さん、今日の現場では、どの帽子をかぶりますか。この白い帽子はどうですか。",
          romaji: "Suzuki-san, kyou no genba dewa, dono boushi o kaburimasu ka. Kono shiroi boushi wa dou desu ka.",
          text_id: "Suzuki-san, di tempat kerja hari ini, topi mana yang harus dipakai? Bagaimana dengan topi putih ini?",
        },
        {
          speaker: "Suzuki (鈴木)",
          text_ja: "白い帽子はちょっと古いですから、あそこの新しい青い帽子をかぶってください。",
          romaji: "Shiroi boushi wa chotto furui desu kara, asoko no atarashii aoi boushi o kabutte kudasai.",
          text_id: "Topi putih itu sudah agak usang, jadi tolong kenakan topi biru yang baru di sebelah sana.",
        },
        {
          speaker: "Agus (アグス)",
          text_ja: "はい。めがねも必要ですか。",
          romaji: "Hai. Megane mo hitsuyou desu ka.",
          text_id: "Baik. Apakah kacamata pelindung juga diperlukan?",
        },
        {
          speaker: "Suzuki (鈴木)",
          text_ja: "今日の現場は明るいですから、めがねはいりませんよ。",
          romaji: "Kyou no genba wa akarui desu kara, megane wa irimasen yo.",
          text_id: "Karena area kerja hari ini terang, kacamata tidak diperlukan kok.",
        },
        {
          speaker: "Agus (アグス)",
          text_ja: "わかりました。じゃあ、青い帽子にします。",
          romaji: "Wakarimashita. Jaa, aoi boushi ni shimasu.",
          text_id: "Saya mengerti. Kalau begitu, saya pakai topi yang biru.",
        },
      ],
      explanation: {
        summary: "Jawaban yang benar adalah ③ (Topi biru baru tanpa kacamata).",
        logic: "Suzuki-san meminta Agus tidak memakai topi putih karena sudah usang (古いですから) dan menyuruh memakai topi biru yang baru (新しい青い帽子). Ketika ditanya soal kacamata pelindung, Suzuki menjelaskan bahwa tempat kerja hari ini terang (明るいですから), sehingga kacamata tidak diperlukan (めがねはいりません).",
        distractor: "• Opsi ① & ②: Topi putih ditolak karena usang (古い).\n• Opsi ④: Topi biru benar, tetapi kacamata tidak diperlukan.",
        grammarRule: "Pola Bab 8: Kata sifat modifikasi nomina (新しい青い帽子) dan partikel alasan ~から (古いですから / 明るいですから).",
      },
    },

    {
      id: 2,
      type: "gambar",
      section_ja: "第1部：イラスト理解",
      section_id: "Bagian 1: Pemahaman Ilustrasi",
      audioTimestamp: "01:12",
      audioStartSeconds: 72.7,
      question_ja: "男の人のカバンはどれですか。",
      question_ruby: "<ruby>男<rt>おとこ</rt></ruby>の<ruby>人<rt>ひと</rt></ruby>のカバンはどれですか。",
      question_romaji: "Otoko no hito no kaban wa dore desu ka.",
      question_id: "Tas milik laki-laki tersebut yang mana?",
      image: "assets/bab_08/q2.png",
      options: [
        { id: "1", symbol: "①", text_ja: "① 上の棚の大きい黒いカバン", text_id: "Rak atas: tas hitam besar" },
        { id: "2", symbol: "②", text_ja: "② 上の棚の小さい白いカバン", text_id: "Rak atas: tas putih kecil" },
        { id: "3", symbol: "③", text_ja: "③ 下の棚の大きい黒いカバン", text_id: "Rak bawah: tas hitam besar" },
        { id: "4", symbol: "④", text_ja: "④ 下の棚の小さい白いカバン", text_id: "Rak bawah: tas putih kecil" },
      ],
      correctAnswer: "4",
      dialogue: [
        {
          speaker: "Dadan (ダダン)",
          text_ja: "田中さん、私のカバンはどこにありますか。",
          romaji: "Tanaka-san, watashi no kaban wa doko ni arimasu ka.",
          text_id: "Tanaka-san, di mana tas saya berada?",
        },
        {
          speaker: "Tanaka (田中)",
          text_ja: "あそこの棚にありますよ。上ですか、下ですか。",
          romaji: "Asoko no tana ni arimasu yo. Ue desu ka, shita desu ka.",
          text_id: "Ada di rak sebelah sana. Di bagian atas atau bawah?",
        },
        {
          speaker: "Dadan (ダダン)",
          text_ja: "上の棚ではありません。下の棚です。",
          romaji: "Ue no tana dewa arimasen. Shita no tana desu.",
          text_id: "Bukan di rak atas. Di rak bawah.",
        },
        {
          speaker: "Tanaka (田中)",
          text_ja: "下の棚ですね。あの大きい黒いカバンですか。",
          romaji: "Shita no tana desu ne. Ano ookii kuroi kaban desu ka.",
          text_id: "Rak bawah ya. Apakah tas hitam yang besar itu?",
        },
        {
          speaker: "Dadan (ダダン)",
          text_ja: "いいえ、あの黒いカバンはアグスさんのです。私のは、小さくて白いカバンです。",
          romaji: "Iie, ano kuroi kaban wa Agus-san no desu. Watashi no wa, chiisakute shiroi kaban desu.",
          text_id: "Bukan, tas hitam itu milik Agus-san. Milik saya yang kecil dan berwarna putih.",
        },
        {
          speaker: "Tanaka (田中)",
          text_ja: "ああ、これですね。どうぞ。",
          romaji: "Aa, kore desu ne. Douzo.",
          text_id: "Ah, yang ini ya. Silakan.",
        },
        {
          speaker: "Dadan (ダダン)",
          text_ja: "ありがとうございます。",
          romaji: "Arigatou gozaimasu.",
          text_id: "Terima kasih banyak.",
        },
      ],
      explanation: {
        summary: "Jawaban yang benar adalah ④ (Rak bawah, tas putih kecil).",
        logic: "Dadan mengeliminasi rak atas ('上の棚ではありません。下の棚です'). Di rak bawah ada tas hitam besar, namun Dadan menyatakan tas hitam tersebut kepunyaan Agus, sedangkan miliknya adalah yang kecil dan putih ('小さくて白いカバン').",
        distractor: "• Opsi ① & ②: Salah rak (berada di rak atas).\n• Opsi ③: Berada di rak bawah, tetapi tas hitam besar adalah milik Agus.",
        grammarRule: "Pola Bab 8: Bentuk penyambung kata sifat-i (~くて) dan penunjuk kepemilikan (~のです).",
      },
    },

    {
      id: 3,
      type: "gambar",
      section_ja: "第1部：イラスト理解",
      section_id: "Bagian 1: Pemahaman Ilustrasi",
      audioTimestamp: "02:11",
      audioStartSeconds: 131.4,
      question_ja: "男の人はどの弁当を買いますか。",
      question_ruby: "<ruby>男<rt>おとこ</rt></ruby>の<ruby>人<rt>ひと</rt></ruby>はどの<ruby>弁当<rt>べんとう</rt></ruby>を<ruby>買<rt>か</rt></ruby>いますか。",
      question_romaji: "Otoko no hito wa dono bentou o kaimasu ka.",
      question_id: "Laki-laki tersebut akan membeli bento yang mana?",
      image: "assets/bab_08/q3.png",
      options: [
        { id: "1", symbol: "①", text_ja: "① 肉の弁当（800円）", text_id: "Bento Daging (800 yen)" },
        { id: "2", symbol: "②", text_ja: "② 魚の弁当（500円）", text_id: "Bento Ikan (500 yen)" },
        { id: "3", symbol: "③", text_ja: "③ 熱いラーメン（500円）", text_id: "Ramen Panas (500 yen)" },
        { id: "4", symbol: "④", text_ja: "④ 冷たいサンドイッチ（500円）", text_id: "Sandwich Dingin (500 yen)" },
      ],
      correctAnswer: "2",
      dialogue: [
        {
          speaker: "Sigit (シギット)",
          text_ja: "鈴木さん、お昼の弁当はどれがいいですか。",
          romaji: "Suzuki-san, ohiru no bentou wa dore ga ii desu ka.",
          text_id: "Suzuki-san, bento makan siang mana yang bagus ya?",
        },
        {
          speaker: "Suzuki (鈴木)",
          text_ja: "この800円の肉の弁当はどうですか。とてもおいしいですよ。",
          romaji: "Kono happyaku-en no niku no bentou wa dou desu ka. Totemo oishii desu yo.",
          text_id: "Bagaimana dengan bento daging seharga 800 yen ini? Sangat enak lho.",
        },
        {
          speaker: "Sigit (シギット)",
          text_ja: "おいしそうですね。でも、800円はちょっと高いですね。500円ぐらいの安いのがいいです。",
          romaji: "Oishisou desu ne. Demo, happyaku-en wa chotto takai desu ne. Gohyakuen gurai no yasui no ga ii desu.",
          text_id: "Kelihatannya enak ya. Tapi 800 yen agak mahal ya. Lebih baik yang murah sekitar 500 yen.",
        },
        {
          speaker: "Suzuki (鈴木)",
          text_ja: "じゃあ、500円の魚の弁当か、熱いラーメンはどうですか。",
          romaji: "Jaa, gohyaku-en no sakana no bentou ka, atsui raamen wa dou desu ka.",
          text_id: "Kalau begitu, bagaimana dengan bento ikan 500 yen, atau ramen panas?",
        },
        {
          speaker: "Sigit (シギット)",
          text_ja: "今日はとても暑いですから、熱いラーメンはあまりよくないです。冷たいお茶と一緒に、魚の弁当にします。",
          romaji: "Kyou wa totemo atsui desu kara, atsui raamen wa amari yokunai desu. Tsumetai ocha to issho ni, sakana no bentou ni shimasu.",
          text_id: "Hari ini sangat panas, jadi ramen panas kurang pas. Bersama teh dingin, saya pilih bento ikan saja.",
        },
        {
          speaker: "Suzuki (鈴木)",
          text_ja: "はい、いいですね。",
          romaji: "Hai, ii desu ne.",
          text_id: "Ya, pilihan bagus.",
        },
      ],
      explanation: {
        summary: "Jawaban yang benar adalah ② (Bento Ikan seharga 500 yen).",
        logic: "Sigit menolak bento daging 800 yen karena mahal (高い) dan mencari yang sekitar 500 yen (安い). Di antara pilihan 500 yen, Sigit menolak ramen panas karena suhu hari ini sangat panas (今日はとても暑いですから、熱いラーメンはあまりよくない), dan memutuskan mengambil bento ikan (魚の弁当にします).",
        distractor: "• Opsi ①: Ditolak karena terlalu mahal (800 yen).\n• Opsi ③: Ditolak karena kuah panas tidak cocok di hari yang gerah.\n• Opsi ④: Sandwich tidak pernah dipilih.",
        grammarRule: "Pola Bab 8: Perbandingan harga (高い vs 安い), suhu udara (暑い), suhu makanan (熱い vs 冷たい), dan partikel keputusan ~にします.",
      },
    },

    {
      id: 4,
      type: "gambar",
      section_ja: "第1部：イラスト理解",
      section_id: "Bagian 1: Pemahaman Ilustrasi",
      audioTimestamp: "03:16",
      audioStartSeconds: 196.5,
      question_ja: "明日のミーティングは何時に始まりますか。",
      question_ruby: "<ruby>明日<rt>あした</rt></ruby>のミーティングは<ruby>何時<rt>なんじ</rt></ruby>に<ruby>始<rt>はじ</rt></ruby>まりますか。",
      question_romaji: "Ashita no miitingu wa nanji ni hajimarimasu ka.",
      question_id: "Rapat besok akan dimulai pada pukul berapa?",
      image: "assets/bab_08/q4.png",
      options: [
        { id: "1", symbol: "①", text_ja: "① 7時30分（07:30）", text_id: "Pukul 07:30 (Mulai pembersihan)" },
        { id: "2", symbol: "②", text_ja: "② 8時00分（08:00）", text_id: "Pukul 08:00 (Rapat dimulai)" },
        { id: "3", symbol: "③", text_ja: "③ 8時15分（08:15）", text_id: "Pukul 08:15 (Pengecoh)" },
        { id: "4", symbol: "④", text_ja: "④ 8時30分（08:30）", text_id: "Pukul 08:30 (Waktu normal rutin)" },
      ],
      correctAnswer: "2",
      dialogue: [
        {
          speaker: "Narong (ナロン)",
          text_ja: "山田さん、明日の朝のミーティングは何時ですか。いつもは8時半ですね。",
          romaji: "Yamada-san, ashita no asa no miitingu wa nanji desu ka. Itsumo wa hachi-ji han desu ne.",
          text_id: "Yamada-san, rapat besok pagi jam berapa ya? Biasanya jam 8:30 kan.",
        },
        {
          speaker: "Yamada (山田)",
          text_ja: "ええ、いつもは8時半ですが、明日は工場長が早く来ますから、8時に始まります。",
          romaji: "Ee, itsumo wa hachi-ji han desu ga, ashita wa kouchouchou ga hayaku kimasu kara, hachi-ji ni hajimarimasu.",
          text_id: "Ya, biasanya jam 8:30, tapi besok kepala pabrik datang lebih awal, jadi akan dimulai jam 8:00.",
        },
        {
          speaker: "Narong (ナロン)",
          text_ja: "8時ですね。掃除はミーティングの後ですか。",
          romaji: "Hachi-ji desu ne. Souji wa miitingu no ato desu ka.",
          text_id: "Jam 8:00 ya. Apakah bersih-bersih dilakukan setelah rapat?",
        },
        {
          speaker: "Yamada (山田)",
          text_ja: "いいえ、掃除はミーティングの前です。7時半から8時まで掃除をします。",
          romaji: "Iie, souji wa miitingu no mae desu. Shichi-ji han kara hachi-ji made souji o shimasu.",
          text_id: "Bukan, bersih-bersih sebelum rapat. Kita bersih-bersih dari jam 7:30 sampai jam 8:00.",
        },
        {
          speaker: "Narong (ナロン)",
          text_ja: "わかりました。じゃあ、明日は8時までに準備します。",
          romaji: "Wakarimashita. Jaa, ashita wa hachi-ji made ni junbi shimasu.",
          text_id: "Baik, saya mengerti. Kalau begitu besok saya akan bersiap sebelum jam 8:00.",
        },
      ],
      explanation: {
        summary: "Jawaban yang benar adalah ② (Pukul 08:00 / 8時00分).",
        logic: "Narong memastikan apakah besok rapat tetap jam 8:30 seperti biasanya (いつもは8時半). Yamada mengoreksi bahwa karena kepala pabrik datang lebih awal (早く来ますから), rapat dimajukan menjadi pukul 8:00 (8時に始まります). Pukul 7:30 adalah dimulainya kegiatan bersih-bersih sebelum rapat.",
        distractor: "• Opsi ①: 07:30 adalah awal jam bersih-bersih.\n• Opsi ④: 08:30 adalah jadwal hari biasa sebelum diubah.",
        grammarRule: "Pola Bab 8 & Bab 4: Kata sifat cepat/awal (早い / 早く), pergeseran jadwal (～ですが), dan penanda jam (~時に).",
      },
    },

    {
      id: 5,
      type: "cerita",
      section_ja: "第2部：会話・課題理解",
      section_id: "Bagian 2: Pemahaman Percakapan",
      audioTimestamp: "04:30",
      audioStartSeconds: 270.7,
      question_ja: "新しい実習生のサントスさんはどんな人ですか。",
      question_ruby: "<ruby>新<rt>あたら</rt></ruby>しい<ruby>実習生<rt>じっしゅうせい</rt></ruby>のサントスさんはどんな<ruby>人<rt>ひと</rt></ruby>ですか。",
      question_romaji: "Atarashii jisshuusei no Santos-san wa donna hito desu ka.",
      question_id: "Seperti apakah sosok Santos-san, anak magang yang baru?",
      options: [
        { id: "1", symbol: "①", text_ja: "① 静かで、背が高い人", text_id: "Orang yang pendiam dan bertubuh tinggi" },
        { id: "2", symbol: "②", text_ja: "② 静かですが、仕事がまじめな人", text_id: "Orang yang pendiam tetapi rajin bekerja" },
        { id: "3", symbol: "③", text_ja: "③ 元気で、明るい人", text_id: "Orang yang bersemangat dan ceria" },
        { id: "4", symbol: "④", text_ja: "④ 背が高くて、力がある人", text_id: "Orang yang bertubuh tinggi dan bertenaga" },
      ],
      correctAnswer: "3",
      dialogue: [
        {
          speaker: "Tanaka (田中)",
          text_ja: "アグスさん、新しい実習生のサントスさんはもう現場に来ましたか。",
          romaji: "Agus-san, atarashii jisshuusei no Santos-san wa mou genba ni kimashita ka.",
          text_id: "Agus-san, apakah anak magang baru Santos-san sudah datang ke lokasi kerja?",
        },
        {
          speaker: "Agus (アグス)",
          text_ja: "はい、来ましたよ。",
          romaji: "Hai, kimashita yo.",
          text_id: "Ya, sudah datang kok.",
        },
        {
          speaker: "Tanaka (田中)",
          text_ja: "サントスさんはどんな人ですか。静かな人ですか。",
          romaji: "Santos-san wa donna hito desu ka. Shizuka na hito desu ka.",
          text_id: "Santos-san itu orang yang bagaimana? Apakah orang yang pendiam?",
        },
        {
          speaker: "Agus (アグス)",
          text_ja: "いいえ、静かじゃありません。いつも元気で、とても明るい人です。仕事もまじめですよ。",
          romaji: "Iie, shizuka ja arimasen. Itsumo genki de, totemo akarui hito desu. Shigoto mo majime desu yo.",
          text_id: "Bukan, tidak pendiam. Orangnya selalu bersemangat dan sangat ceria. Kerjanya juga sungguh-sungguh.",
        },
        {
          speaker: "Tanaka (田中)",
          text_ja: "そうですか。背が高いですか。",
          romaji: "Sou desu ka. Se ga takai desu ka.",
          text_id: "Begitu ya. Apakah badannya tinggi?",
        },
        {
          speaker: "Agus (アグス)",
          text_ja: "いいえ、背はあまり高くないですが、力持ちですよ。",
          romaji: "Iie, se wa amari takakunai desu ga, chikaramochi desu yo.",
          text_id: "Tidak, badannya tidak begitu tinggi, tetapi tenaganya kuat lho.",
        },
        {
          speaker: "Tanaka (田中)",
          text_ja: "それは頼もしいですね。",
          romaji: "Sore wa tanomoshii desu ne.",
          text_id: "Wah, itu sangat bisa diandalkan ya.",
        },
      ],
      explanation: {
        summary: "Jawaban yang benar adalah ③ (元気で、明るい人 / Orang yang bersemangat dan ceria).",
        logic: "Agus membantah dugaan bahwa Santos orang pendiam (いいえ、静かじゃありません). Santos dideskripsikan sebagai orang yang bersemangat dan ceria (いつも元気で、とても明るい人です). Terkait tinggi badan, Agus juga membantah bahwa Santos tinggi (背はあまり高くない).",
        distractor: "• Opsi ① & ②: Sifat pendiam (静か) sudah dibantah dengan tegas.\n• Opsi ④: Santos tidak bertubuh tinggi.",
        grammarRule: "Pola Bab 8: Pertanyaan karakter (どんな人), negasi sifat-na (静かじゃありません), dan penyambung sifat-na (~で).",
      },
    },

    {
      id: 6,
      type: "cerita",
      section_ja: "第2部：会話・課題理解",
      section_id: "Bagian 2: Pemahaman Percakapan",
      audioTimestamp: "05:35",
      audioStartSeconds: 335.8,
      question_ja: "今日の午前中の天気はどうですか。",
      question_ruby: "<ruby>今日<rt>きょう</rt></ruby>の<ruby>午前中<rt>ごぜんちゅう</rt></ruby>の<ruby>天気<rt>てんき</rt></ruby>はどうですか。",
      question_romaji: "Kyou no gozenchuu no tenki wa dou desu ka.",
      question_id: "Bagaimanakah cuaca pada pagi/siang hari ini?",
      options: [
        { id: "1", symbol: "①", text_ja: "① 暖かくて、天気がいい", text_id: "Hangat dan cuacanya cerah" },
        { id: "2", symbol: "②", text_ja: "② 晴れですが、寒くて風が強い", text_id: "Cerah, tetapi dingin dan berangin kencang" },
        { id: "3", symbol: "③", text_ja: "③ 雪が降って、とても寒い", text_id: "Turun salju dan sangat dingin" },
        { id: "4", symbol: "④", text_ja: "④ 雨が降って、空が暗い", text_id: "Turun hujan dan langit gelap" },
      ],
      correctAnswer: "2",
      dialogue: [
        {
          speaker: "Dadan (ダダン)",
          text_ja: "鈴木さん、おはようございます。今日はとても寒いですね。",
          romaji: "Suzuki-san, ohayou gozaimasu. Kyou wa totemo samui desu ne.",
          text_id: "Suzuki-san, selamat pagi. Hari ini sangat dingin ya.",
        },
        {
          speaker: "Suzuki (鈴木)",
          text_ja: "おはよう、ダダンさん。そうですね。昨日は暖かかったですが、今日は風が強くて寒いです。",
          romaji: "Ohayou, Dadan-san. Sou desu ne. Kinou wa atatakakatta desu ga, kyou wa kaze ga tsuyokute samui desu.",
          text_id: "Selamat pagi, Dadan-san. Benar sekali. Kemarin memang hangat, tetapi hari ini anginnya kencang dan dingin.",
        },
        {
          speaker: "Dadan (ダダン)",
          text_ja: "雪が降りますか。",
          romaji: "Yuki ga furimasu ka.",
          text_id: "Apakah akan turun salju?",
        },
        {
          speaker: "Suzuki (鈴木)",
          text_ja: "いいえ、雪は降りませんよ。晴れですが、空気が冷たいです。午後はあまり寒くないでしょう。",
          romaji: "Iie, yuki wa furimasen yo. Hare desu ga, kuuki ga tsumetai desu. Gogo wa amari samukunai deshou.",
          text_id: "Tidak, salju tidak akan turun. Cuacanya cerah, tetapi udaranya dingin. Siang nanti mungkin tidak begitu dingin.",
        },
        {
          speaker: "Dadan (ダダン)",
          text_ja: "そうですか。良かったです。",
          romaji: "Sou desu ka. Yokatta desu.",
          text_id: "Begitu ya. Syukurlah.",
        },
      ],
      explanation: {
        summary: "Jawaban yang benar adalah ② (晴れですが、寒くて風が強い / Cerah, tetapi dingin dan berangin).",
        logic: "Suzuki mengontraskan cuaca kemarin dan hari ini: kemarin memang hangat (昨日は暖かかったですが), tetapi hari ini angin kencang dan dingin (今日は風が強くて寒いです). Cuacanya cerah dan tidak ada salju, namun udaranya dingin (晴れですが、空気が冷たいです).",
        distractor: "• Opsi ①: Menjebak cuaca kemarin (暖かかった).\n• Opsi ③: Salju tidak turun (雪は降りません).\n• Opsi ④: Tidak ada hujan maupun mendung.",
        grammarRule: "Pola Bab 8: Bentuk lampau kata sifat-i (暖かかった), penyambung sifat-i (~くて), dan partikel pertentangan ~が.",
      },
    },

    {
      id: 7,
      type: "cerita",
      section_ja: "第2部：会話・課題理解",
      section_id: "Bagian 2: Pemahaman Percakapan",
      audioTimestamp: "06:33",
      audioStartSeconds: 393.8,
      question_ja: "男の人はまず何をしますか。",
      question_ruby: "<ruby>男<rt>おとこ</rt></ruby>の<ruby>人<rt>ひと</rt></ruby>はまず<ruby>何<rt>なに</rt></ruby>をしますか。",
      question_romaji: "Otoko no hito wa mazu nani o shimasu ka.",
      question_id: "Apa yang akan dilakukan laki-laki tersebut paling pertama?",
      options: [
        { id: "1", symbol: "①", text_ja: "① お風呂を掃除します", text_id: "Membersihkan kamar mandi" },
        { id: "2", symbol: "②", text_ja: "② テーブルを拭きます", text_id: "Mengelap meja makan" },
        { id: "3", symbol: "③", text_ja: "③ 台所のごみを捨てます", text_id: "Membuang sampah dapur" },
        { id: "4", symbol: "④", text_ja: "④ 寮の部屋で休みます", text_id: "Beristirahat di kamar asrama" },
      ],
      correctAnswer: "3",
      dialogue: [
        {
          speaker: "Narong (ナロン)",
          text_ja: "指導員、寮の部屋の掃除が終わりました。",
          romaji: "Shidouin, ryou no heya no souji ga owarimashita.",
          text_id: "Pembimbing, pembersihan kamar asrama sudah selesai.",
        },
        {
          speaker: "Shidouin (指導員)",
          text_ja: "ご苦労さま。でも、台所はどうですか。きれいですか。",
          romaji: "Gokurousama. Demo, daidokoro wa dou desu ka. Kirei desu ka.",
          text_id: "Terima kasih atas kerja kerasnya. Tapi, bagaimana dengan dapur? Apakah sudah bersih?",
        },
        {
          speaker: "Narong (ナロン)",
          text_ja: "あ、台所はまだ汚いです。",
          romaji: "A, daidokoro wa mada kitanai desu.",
          text_id: "Ah, dapur masih kotor.",
        },
        {
          speaker: "Shidouin (指導員)",
          text_ja: "じゃあ、まず台所のごみを捨ててください。それから、テーブルを拭いてください。最後にお風呂を掃除しましょう。",
          romaji: "Jaa, mazu daidokoro no gomi o sutete kudasai. Sorekara, teeburu o fuite kudasai. Saigo ni ofuro o souji shimashou.",
          text_id: "Kalau begitu, pertama-tama buanglah sampah dapur. Setelah itu, tolong lap mejanya. Terakhir, mari bersihkan kamar mandi.",
        },
        {
          speaker: "Narong (ナロン)",
          text_ja: "はい、わかりました。すぐごみを捨てます。",
          romaji: "Hai, wakarimashita. Sugu gomi o sutemasu.",
          text_id: "Baik, saya paham. Saya akan segera membuang sampahnya.",
        },
      ],
      explanation: {
        summary: "Jawaban yang benar adalah ③ (台所のごみを捨てます / Membuang sampah dapur).",
        logic: "Instruktur memberikan urutan 3 kegiatan: (1) Pertama-tama buang sampah dapur (まず台所のごみを捨ててください), (2) Setelah itu lap meja (それからテーブルを拭いてください), dan (3) Terakhir bersihkan kamar mandi (最後にお風呂を掃除しましょう). Pertanyaan secara spesifik menanyakan apa yang dilakukan PALING PERTAMA (まず).",
        distractor: "• Opsi ①: Membersihkan kamar mandi adalah giliran terakhir (最後に).\n• Opsi ②: Mengelap meja adalah giliran kedua (それから).\n• Opsi ④: Narong belum selesai bertugas.",
        grammarRule: "Pola Bab 8 & Bab 6: Bersih vs kotor (きれい vs 汚い) dan penanda urutan kronologis (まず、それから、最後に).",
      },
    },

    {
      id: 8,
      type: "cerita",
      section_ja: "第2部：会話・課題理解",
      section_id: "Bagian 2: Pemahaman Percakapan",
      audioTimestamp: "07:29",
      audioStartSeconds: 449.5,
      question_ja: "女の人はどの扇風機を買いますか。",
      question_ruby: "<ruby>女<rt>おんな</rt></ruby>の<ruby>人<rt>ひと</rt></ruby>はどの<ruby>扇風機<rt>せんぷうき</rt></ruby>を<ruby>買<rt>か</rt></ruby>いますか。",
      question_romaji: "Onna no hito wa dono senpuuki o kaimasu ka.",
      question_id: "Perempuan tersebut akan membeli kipas angin yang mana?",
      options: [
        { id: "1", symbol: "①", text_ja: "① 2,000円の小さい扇風機", text_id: "Kipas angin kecil seharga 2.000 yen" },
        { id: "2", symbol: "②", text_ja: "② 安くて、音が大きい扇風機", text_id: "Kipas angin murah yang suaranya bising" },
        { id: "3", symbol: "③", text_ja: "③ 4,000円の静かで涼しい扇風機", text_id: "Kipas angin 4.000 yen yang hening dan sejuk" },
        { id: "4", symbol: "④", text_ja: "④ 扇風機は買いません", text_id: "Tidak jadi membeli kipas angin" },
      ],
      correctAnswer: "3",
      dialogue: [
        {
          speaker: "Tenchou (店員)",
          text_ja: "いらっしゃいませ。扇風機をお探しですか。",
          romaji: "Irasshaimase. Senpuuki o osagashi desu ka.",
          text_id: "Selamat datang. Apakah Anda sedang mencari kipas angin?",
        },
        {
          speaker: "Wati (ワティ)",
          text_ja: "はい。寮の部屋が暑いですから、扇風機が欲しいです。この2,000円の小さいのはどうですか。",
          romaji: "Hai. Ryou no heya ga atsui desu kara, senpuuki ga hoshii desu. Kono nisen-en no chiisai no wa dou desu ka.",
          text_id: "Ya. Karena kamar asrama panas, saya ingin kipas angin. Bagaimana dengan yang kecil seharga 2.000 yen ini?",
        },
        {
          speaker: "Tenchou (店員)",
          text_ja: "それはとても安いです。でも、風があまり強くなくて、涼しくないですよ。こちらの白い扇風機は4,000円ですが、とても涼しくて音も静かです。",
          romaji: "Sore wa totemo yasui desu. Demo, kaze ga amari tsuyokunakute, suzushikunai desu yo. Kochira no shiroi senpuuki wa yonsen-en desu ga, totemo suzushikute oto mo shizuka desu.",
          text_id: "Itu sangat murah. Tetapi hembusan anginnya tidak begitu kuat dan tidak sejuk lho. Kipas putih seharga 4.000 yen di sebelah sini sangat sejuk dan suaranya hening.",
        },
        {
          speaker: "Wati (ワティ)",
          text_ja: "そうですか。2,000円のは安いですが、涼しくないのは困りますね。じゃあ、こちらの静かで涼しいほうにします。",
          romaji: "Sou desu ka. Nisen-en no wa yasui desu ga, suzushikunai no wa komarimasu ne. Jaa, kochira no shizuka de suzushii hou ni shimasu.",
          text_id: "Begitu ya. Yang 2.000 yen memang murah, tapi kalau tidak sejuk repot juga ya. Kalau begitu, saya ambil yang hening dan sejuk ini saja.",
        },
        {
          speaker: "Tenchou (店員)",
          text_ja: "ありがとうございます。",
          romaji: "Arigatou gozaimasu.",
          text_id: "Terima kasih banyak.",
        },
      ],
      explanation: {
        summary: "Jawaban yang benar adalah ③ (4,000円の静かで涼しい扇風機 / Kipas angin 4.000 yen yang hening dan sejuk).",
        logic: "Wati membatalkan niat membeli kipas kecil 2.000 yen karena diinformasikan hembusannya tidak kuat dan tidak sejuk (涼しくない). Penjual merekomendasikan kipas 4.000 yen yang sejuk dan hening (涼しくて音も静かです). Wati pun memutuskan membeli kipas 4.000 yen tersebut (こちらの静かで涼しいほうにします).",
        distractor: "• Opsi ①: Dibatalkan karena tidak sejuk.\n• Opsi ②: Distraktor bising dan murah.\n• Opsi ④: Wati tetap membeli barang.",
        grammarRule: "Pola Bab 8: Perubahan keputusan (Decision flip), kata sifat sejuk vs gerah (涼しい vs 暑い), hening (静か), dan bentuk pilihan ~のほうにします.",
      },
    },
  ],
};
